name = "bakkah-display"
compatibility_date = "2026-07-17"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "D1_BACKEND"
database_name = "bakkah-display-db"
database_id = "134889b3-cd16-461c-b4c8-f8520216bb70"

[env.production.vars]
ENVIRONMENT = "production"

[[env.production.d1_databases]]
binding = "D1_BACKEND"
database_name = "bakkah-display-db"
database_id = "134889b3-cd16-461c-b4c8-f8520216bb70"
